services:
  - type: web
    name: StudentManagementApp
    env: docker
    repo: https://github.com/Yuvathaarani-ravanan/Student-Management-App.git
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: MongoDBSettings__ConnectionURI
        value: mongodb://192.168.55.99:27017
      - key: MongoDBSettings__DatabaseName
        value: Studentdb
      - key: MongoDBSettings__UserCollectionName
        value: Users
      - key: TokenKey
        value: 9rN2xJkLp7QzA1vF6YdXr4UeMjWc8HgT
